# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download 461 targeting pack
      uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9 # 1.6.0
      id: downloadfile  # Remember to give an ID if you need the output filename
      with:
          url: "https://dotnet.microsoft.com/zh-tw/download/dotnet-framework/thank-you/net451-developer-pack-offline-installer"
          target: public/

    - name: Install targeting pack
      shell: cmd
      working-directory: public
      run: net451-developer-pack-offline-installer /q
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: show
      run: |
        ls -R .
    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v4.5.0
    #   with:
    #     name: # optional, default is artifact
    #     path: 
          
